# Generated by Django 2.1.4 on 2019-02-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=128, unique=True)),
                ('Season02_Matches', models.IntegerField(max_length=64)),
                ('Season03_Matches', models.IntegerField(max_length=64)),
                ('Season04_Matches', models.IntegerField(max_length=64)),
                ('Season05_Matches', models.IntegerField(max_length=64)),
                ('Season02_Wins', models.IntegerField(max_length=64)),
                ('Season03_Wins', models.IntegerField(max_length=64)),
                ('Season04_Wins', models.IntegerField(max_length=64)),
                ('Season05_Wins', models.IntegerField(max_length=64)),
            ],
        ),
    ]
