# Generated by Django 2.1.4 on 2019-02-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalMatches', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='Season02_Matches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Season02_Wins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Season03_Matches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Season03_Wins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Season04_Matches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Season04_Wins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Season05_Matches',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Season05_Wins',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='playermatches',
            name='PlayerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerstats.Player'),
        ),
    ]
