# Generated by Django 2.1.4 on 2019-02-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0002_auto_20190212_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatches',
            name='PlayerName',
        ),
        migrations.AddField(
            model_name='player',
            name='TotalMatches',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerMatches',
        ),
    ]
