# Generated by Django 2.1.4 on 2019-02-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0003_auto_20190213_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='TotalKills',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
