# Generated by Django 2.1.4 on 2019-02-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0005_auto_20190213_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Headshotratio',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='Killratio',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='Mostkills',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season02_Headshot',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season02_Kills',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season03_Headshot',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season03_Kills',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season04_Headshot',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season04_Kills',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season05_Headshot',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='Season05_Kills',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='TotalHeadshot',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='TotalKills',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='static/playerstats/download.jpg', upload_to='static/'),
        ),
    ]
