# Generated by Django 2.1.4 on 2019-02-15 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerstats', '0006_auto_20190214_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='picture',
        ),
    ]
